spring:
  application:
    name: card-manager
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/${MYSQL_URL}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
server:
  port: 8080