spring:
  application:
    name: card-manager
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    username: admin
    password: admin
    url: jdbc:mysql://localhost:3306/card
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
server:
  port: 8080